# Generated by Django 4.2.19 on 2025-03-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelescopeObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telescope', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('observation_date', models.DateTimeField()),
                ('target_name', models.CharField(blank=True, max_length=255, null=True)),
                ('observation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-observation_date'],
            },
        ),
        migrations.CreateModel(
            name='TelescopeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telescope', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('current_instrument', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update', models.DateTimeField()),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Telescope Statuses',
            },
        ),
    ]
